nodeLinker: pnp

packageExtensions:
  vite@*:
    dependencies:
      supports-color: "*"
  debug@*:
    dependencies:
      supports-color: "*"

pnpEnableEsmLoader: true

pnpFallbackMode: dependencies-only

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.2.2.cjs